export const seedData = {
  inventory: [
    {
      nombre: 'Laptop Dell XPS 13',
      sku: 'DELL-XPS-13',
      precio: 1299.99,
      stock: 15,
      descripcion: 'Laptop ultraligera de 13 pulgadas con procesador Intel de última generación',
    },
    {
      nombre: 'Mouse Logitech MX Master 3',
      sku: 'LOG-MX-MASTER-3',
      precio: 99.99,
      stock: 45,
      descripcion: 'Mouse profesional con múltiples botones programables',
    },
    {
      nombre: 'Teclado Mecánico Corsair K95',
      sku: 'COR-K95-RGB',
      precio: 199.99,
      stock: 22,
      descripcion: 'Teclado mecánico con iluminación RGB programable',
    },
    {
      nombre: 'Monitor LG 27" UltraWide',
      sku: 'LG-27-UW',
      precio: 499.99,
      stock: 8,
      descripcion: 'Monitor ultraancho de 27 pulgadas 1440p',
    },
    {
      nombre: 'Webcam Logitech C920',
      sku: 'LOG-C920-HD',
      precio: 79.99,
      stock: 30,
      descripcion: 'Cámara web full HD para streaming y conferencias',
    },
    {
      nombre: 'Auriculares Sony WH-1000XM5',
      sku: 'SONY-WH-1000',
      precio: 399.99,
      stock: 12,
      descripcion: 'Auriculares con cancelación de ruido activa',
    },
    {
      nombre: 'SSD Samsung 970 EVO 1TB',
      sku: 'SAM-970-1TB',
      precio: 129.99,
      stock: 50,
      descripcion: 'Unidad SSD NVMe de alta velocidad',
    },
    {
      nombre: 'RAM Corsair Vengeance 32GB',
      sku: 'COR-VENG-32GB',
      precio: 149.99,
      stock: 35,
      descripcion: 'Memoria RAM DDR4 para gaming y productividad',
    },
    {
      nombre: 'Fuente Corsair RM850x 850W',
      sku: 'COR-RM-850',
      precio: 129.99,
      stock: 18,
      descripcion: 'Fuente de poder modular 850W 80+ Gold',
    },
    {
      nombre: 'Router WiFi 6 ASUS AX12',
      sku: 'ASUS-AX12-ROUTER',
      precio: 179.99,
      stock: 24,
      descripcion: 'Router WiFi 6 con mesh support',
    },
    {
      nombre: 'Cable HDMI 2.1 8K',
      sku: 'HDMI-2.1-8K',
      precio: 29.99,
      stock: 100,
      descripcion: 'Cable HDMI 2.1 soporta 8K@60Hz',
    },
    {
      nombre: 'Hub USB-C 7 en 1',
      sku: 'HUB-USBC-7',
      precio: 59.99,
      stock: 40,
      descripcion: 'Hub con múltiples puertos USB-C y HDMI',
    },
  ],
  cobranzas: [
    {
      descripcion: 'Factura #001 - Cliente ABC Corp',
      monto: 5000,
      cliente: 'ABC Corp',
      estado: 'pendiente',
    },
    {
      descripcion: 'Factura #002 - Cliente XYZ Ltd',
      monto: 3500,
      cliente: 'XYZ Ltd',
      estado: 'pendiente',
    },
    {
      descripcion: 'Factura #003 - Cliente Tech Solutions',
      monto: 2000,
      cliente: 'Tech Solutions',
      estado: 'pagado',
    },
    {
      descripcion: 'Factura #004 - Cliente Digital Plus',
      monto: 7500,
      cliente: 'Digital Plus',
      estado: 'vencido',
    },
    {
      descripcion: 'Factura #005 - Cliente Innovation Inc',
      monto: 4200,
      cliente: 'Innovation Inc',
      estado: 'pendiente',
    },
    {
      descripcion: 'Factura #006 - Cliente Global Systems',
      monto: 6800,
      cliente: 'Global Systems',
      estado: 'pagado',
    },
    {
      descripcion: 'Factura #007 - Cliente Future Tech',
      monto: 3100,
      cliente: 'Future Tech',
      estado: 'pendiente',
    },
    {
      descripcion: 'Factura #008 - Cliente Smart Solutions',
      monto: 5500,
      cliente: 'Smart Solutions',
      estado: 'vencido',
    },
    {
      descripcion: 'Factura #009 - Cliente Premium Services',
      monto: 8900,
      cliente: 'Premium Services',
      estado: 'pendiente',
    },
    {
      descripcion: 'Factura #010 - Cliente Next Generation',
      monto: 2750,
      cliente: 'Next Generation',
      estado: 'pagado',
    },
    {
      descripcion: 'Factura #011 - Cliente Advanced Corp',
      monto: 4500,
      cliente: 'Advanced Corp',
      estado: 'pendiente',
    },
    {
      descripcion: 'Factura #012 - Cliente Elite Business',
      monto: 6200,
      cliente: 'Elite Business',
      estado: 'vencido',
    },
  ],
  ventas: [
    {
      cliente: 'ABC Corp',
      producto: 'Laptop Dell XPS 13',
      cantidad: 5,
      monto_total: 6499.95,
      fecha_venta: new Date('2024-03-15').toISOString().split('T')[0],
    },
    {
      cliente: 'XYZ Ltd',
      producto: 'Monitor LG 27"',
      cantidad: 2,
      monto_total: 999.98,
      fecha_venta: new Date('2024-03-16').toISOString().split('T')[0],
    },
    {
      cliente: 'Tech Solutions',
      producto: 'Teclado Mecánico Corsair K95',
      cantidad: 10,
      monto_total: 1999.90,
      fecha_venta: new Date('2024-03-17').toISOString().split('T')[0],
    },
    {
      cliente: 'Digital Plus',
      producto: 'Auriculares Sony WH-1000XM5',
      cantidad: 3,
      monto_total: 1199.97,
      fecha_venta: new Date('2024-03-18').toISOString().split('T')[0],
    },
  ],
}
